# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'deepak-pool'
    backendAzureRmResourceGroupName: 'mademi-rg'
    backendAzureRmStorageAccountName: 'mademisa'
    backendAzureRmContainerName: 'mademistatefiles'
    backendAzureRmKey: 'azurepipeline.terraform.tfstate'

